### ISSUE TITLE
Correct batch size ? 

### ISSUE THREAD

**Issue by achen46** [microsoft/FocalNet#1]
Hello @jwyang ! thanks for the great work ! I was looking at the [log](https://projects4jw.blob.core.windows.net/focalnet/release/classification/log_focalnet_small_srf.txt) for FocalNet-S and the BATCH_SIZE is set to `32`.

However, you mention that BATCH_SIZE should be 128 in the classification [guide](https://github.com/microsoft/FocalNet/tree/main/classification). 

Which one should be ? 

Also, how many nodes/GPUs are used to train this model ?

**Comment by jwyang** [comment]
Hi, @achen46 , thanks for your interest. We used batch size=1024 for training as mentioned in our paper but used 1GPU batch size=128 for measuring the throughput.
