### ISSUE TITLE
no such file or directory tools/train.py

### ISSUE THREAD

**Issue by LeeJinSoo-BIN** [microsoft/FocalNet#11]
i can't find tools/train.py

**Comment by jwyang** [comment]
tools/train.py is for training object detection and segmentation, please put the focalnet code to mmdet (https://github.com/open-mmlab/mmdetection) first and then run with train.py or test.py

**Comment by mattroos** [comment]
@jwyang I'm confused by this as well. Can you clarify further? Should I clone the mmdetection repo, and then copy the FocalNet files into the mmdetection directory structure? Where should the root contents of FocalNet be placed within the mmdetection directory structure?

**Comment by jwyang** [comment]
Hi, @mattroos yes, you are right. You need to clone mmdetection repo and copy the files here (https://github.com/microsoft/FocalNet/tree/main/detection) to the corresponding locations. Please follow the same hierarchy when copying. For example,  you need to copy the files in folder "mmdet/models/backbones" of this repo to the folder mmdet/models/backbones/ under mmdet. Same rule applies to configs.

**Comment by jwyang** [comment]
Also, I am going to put the files into the mmdetection to ease the reproducing of the experiments. Please stay tuned on this repo: https://github.com/FocalNet/FocalNet-MMDetection

**Comment by aliman80** [comment]
For segmentation task, do i need to clone mmsegmentation and then put Focalnet there? Can you guide
