### ISSUE TITLE
Pre-weight of FocalNet backbone for custom segmentation network

### ISSUE THREAD

**Issue by rose-jinyang** [microsoft/FocalNet#14]
Hello
How are you?
Thanks for contributing to this project.
I am going to use FocalNet network as backbone (encoder) of my custom network for semantic segmentation.
I am using my own custom decoder.
Where can I get the pre-trained weight of FocalNet backbone for segmentation?
Of course, you shared the pre-trained models  for segmentation but they were used with ONLY MaskRCNN or UperNet method.

**Comment by jwyang** [comment]
Hi, @rose-jinyang , thanks for your interests.

Please find the image-1k pretrained backbone here:

https://github.com/microsoft/FocalNet#imagenet-1k-pretrained

and the large+ focalnets pretrained on imagenet-21k here:

https://github.com/microsoft/FocalNet#imagenet-22k-pretrained

just simply clip the ckpt hyperlink for downloading the checkpoints.

**Comment by rose-jinyang** [comment]
Thanks for your quick reply.
I think that FocalNet for image classification and FocalNet for segmentation are a little different each other.
Nevertheless, can we use the pre-weights of FocalNet for image classification in segmentation architecture?

**Comment by jwyang** [comment]
yes, you can use it for your segmentation architecture. please make sure all parameters are loaded correctly as the initialization.

**Comment by rose-jinyang** [comment]
Thank you.
