### ISSUE TITLE
When will be released the weights for DINO object detection?

### ISSUE THREAD

**Issue by 25icecreamflavors** [microsoft/FocalNet#15]
Hello, when do you plan to release weights for this model version https://github.com/FocalNet/FocalNet-DINO ?

**Comment by jwyang** [comment]
Hi, @25icecreamflavors ,

We just released the focalnet-large-fl4 pretrained on object365 with DINO, check it out here: 

https://github.com/FocalNet/FocalNet-DINO/blob/main/README.md#model-zoos

**Comment by jaideep11061982** [comment]
@jwyang  how to infer and train.. I am trying to find out

**Comment by jaideep11061982** [comment]
object detection or classifcation

**Comment by jwyang** [comment]
Hi, @jaideep11061982 , 

please try this to train object detection: https://github.com/FocalNet/FocalNet-DINO#training
