### ISSUE TITLE
Focal-Unet --> low complexity, easy to use unet implementation for small dataset domains.

### ISSUE THREAD

**Issue by mohammadrezanaderi4** [microsoft/FocalNet#19]
Dear researchers, please consider checking our unet implementation of the proposed focal modulation block for small datasets problems, specially in medical domains. 
https://github.com/givkashi/Focal-Unet

https://www.researchgate.net/publication/366423296_Focal-UNet_UNet-like_Focal_Modulation_for_Medical_Image_Segmentation

Thanks.

**Comment by jwyang** [comment]
Hi, @mohammadrezanaderi4 , thanks for sharing your work and it is great to know that you guys make it work for medical image segmentation! I will put a pointer referring to your repo.
