### ISSUE TITLE
Pretrained weight ImageNet22K 

### ISSUE THREAD

**Issue by Shiro-LK** [microsoft/FocalNet#20]
Hello, 

I was wondering if the weights mentionned in the paper will be released soon ? 
- focalnet finetuned on imagenet1K after being pretrained on 22K
- focalnet B pretrained on 22K ?

**Comment by jwyang** [comment]
Hi, @Shiro-LK , thanks for your interests, we will release the finetuned focalnet ckpts but do not have plan to pretrain focalnet-base on imagenet-22k.
