### ISSUE TITLE
Setting up ImageNet-22K 

### ISSUE THREAD

**Issue by muzairkhattak** [microsoft/FocalNet#21]
Hi @jwyang,

Thank you for the very interesting work. 

We are planning to train Focal-B on ImageNet-22K. Can you please provide the instructions for preparing ImageNet-22K dataset. 

Currently on the official website, there are two variants available as follows:

Winter 2021 release

- ImageNet21K
- Processed version of ImageNet21K 

Kindly let us know which folder version was used in the main paper for pretraining on IN22K dataset. 

Thank you and kind regards,
Muhammad Uzair

**Comment by jwyang** [comment]
Hi, @muzairkhattak, thanks for your interest in our work! Please use the ImageNet21K as the training data.
