### ISSUE TITLE
where is ckpt_path = "focalnet_base_lrf.pth" and attention or focus scores

### ISSUE THREAD

**Issue by WenY2020** [microsoft/FocalNet#22]
Hello, Jianwei:

I am trying to use focalnet to get some attention/focus scores for my images, I see it perform well here in the modulation map of the below images, and this is exactly what I need, I want to calculate each pixel's attention/focus score, I see in your image, the yellow is with highest attention scores (not sure attention score is the right name, basically I want to see which pixels get more attention from people's eyes).
![image](https://user-images.githubusercontent.com/64662442/216184938-efa53f85-23f4-4259-92f1-55f6d38cd344.png)
And I have two questions:
1. I try to run the code in visualizaiton.ipynb but cannot find "focalnet_base_lrf.pth", where to download it please?
2. I wonder can you give a hint, from which code part, I can get attention scores which shows in the modulation map.

Thank you very much for your help in advance!

Best wishes,
Wen

**Comment by WenY2020** [comment]
I think I get the answer to my first question:  "focalnet_base_lrf.pth" is actually one model of ImageNet-1K Pretrained FocalNet-B.
Not sure the second one...

**Comment by jwyang** [comment]
Hi, @WenY2020 , 

thanks for your interest in our work. Regarding your two questions:

1. You can download the 'focalnet_base_lrf.pth' from this link: https://projects4jw.blob.core.windows.net/focalnet/release/classification/focalnet_base_lrf.pth. 
actually, you can find all the downloadable ckpts from here: https://github.com/microsoft/FocalNet#imagenet-1k-pretrained

This checkpoint is hierarchical which is slightly worse for visualization. I recommend you can also try to use the isotropic focalnets.

2. For visualize the modulation map, you can simply refer to this line of code: https://github.com/microsoft/FocalNet/blob/6de0705ffd4cdb26217c680461e0390a8d5f5c41/classification/focalnet.py#L96

It stores the modulator for each focal modulation block so that you can visualize the magnitude of the modulation maps for all laters.

thanks,
Jianwei

**Comment by jwyang** [comment]
And if you just want to visualize your images, you can directly use this hugging face demo!

https://huggingface.co/spaces/jw2yang/focalnet-modulators

**Comment by WenY2020** [comment]
thank you very much, Jianwei, those are very helpful, 
I wll look into here:  x_out = q*self.modulator,
Great, I need not only the visualization, mainly I need the attention numbers/scores, will need to use it as a feature to feed other models.

**Comment by jwyang** [comment]
Awesome, let me know if you have any further questions.

**Comment by WenY2020** [comment]
thanks you, will do:).

**Comment by 23jisuper** [comment]
> Jianwei 您好：
> 
> 我正在尝试使用 focalnet 为我的图像获取一些注意力/焦点分数，我看到它在下图的调制图中表现良好，这正是我所需要的，我想计算每个像素的注意力/焦点分数，我在你的图像中看到，黄色是注意力分数最高的（不确定注意力分数是正确的名称， 基本上我想看看哪些像素从人们的眼睛中得到了更多的关注）。 ![image](https://user-images.githubusercontent.com/64662442/216184938-efa53f85-23f4-4259-92f1-55f6d38cd344.png)我有两个问题：
> 
> 1. 我尝试在 visualizaiton.ipynb 中运行代码，但找不到“focalnet_base_lrf.pth”，请问在哪里下载它？
> 2. 我想知道您能否给出一个提示，从哪个代码部分，我可以获得显示在调制图中的注意力分数。
> 
> 非常感谢您的提前帮助！
> 
> 最美好的祝愿，温



> Hello, Jianwei:
> 
> I am trying to use focalnet to get some attention/focus scores for my images, I see it perform well here in the modulation map of the below images, and this is exactly what I need, I want to calculate each pixel's attention/focus score, I see in your image, the yellow is with highest attention scores (not sure attention score is the right name, basically I want to see which pixels get more attention from people's eyes). ![image](https://user-images.githubusercontent.com/64662442/216184938-efa53f85-23f4-4259-92f1-55f6d38cd344.png) And I have two questions:
> 
> 1. I try to run the code in visualizaiton.ipynb but cannot find "focalnet_base_lrf.pth", where to download it please?
> 2. I wonder can you give a hint, from which code part, I can get attention scores which shows in the modulation map.
> 
> Thank you very much for your help in advance!
> 
> Best wishes, Wen



> thanks you, will do:).



> Hello, Jianwei:
> 
> I am trying to use focalnet to get some attention/focus scores for my images, I see it perform well here in the modulation map of the below images, and this is exactly what I need, I want to calculate each pixel's attention/focus score, I see in your image, the yellow is with highest attention scores (not sure attention score is the right name, basically I want to see which pixels get more attention from people's eyes). ![image](https://user-images.githubusercontent.com/64662442/216184938-efa53f85-23f4-4259-92f1-55f6d38cd344.png) And I have two questions:
> 
> 1. I try to run the code in visualizaiton.ipynb but cannot find "focalnet_base_lrf.pth", where to download it please?
> 2. I wonder can you give a hint, from which code part, I can get attention scores which shows in the modulation map.
> 
> Thank you very much for your help in advance!
> 
> Best wishes, Wen

您好，请问以下您这热力图的代码可以分享一下吗？
