### ISSUE TITLE
ImageNet pretrain weight is used to initialize Detection Model(e.g. ATSS) or not ?

### ISSUE THREAD

**Issue by YanShuang17** [microsoft/FocalNet#3]
Hi Author, Thanks to open source your nice backbone.

When training Dectection Model, I can't find related codes for loading ImageNet pretrained wight. So the ImageNet pretrained wight is used or not ?

**Comment by jwyang** [comment]
Hi, @YanShuang17 

To train detection model, it does need to load the pretrained weights as shown [here](https://github.com/microsoft/FocalNet/blob/92913f0482ab79f05f2d31af1dbdf31ab72dd016/detection/mmdet/models/backbones/focalnet.py#L443). By default, MMDetection will call this init_weights function. If you specify the pretrained model, then it will load it.

thanks,

**Comment by YanShuang17** [comment]
Ok! Thanks for your reply.
