### ISSUE TITLE
All checkpoint downloads unavailable

### ISSUE THREAD

**Issue by seewhyjay** [microsoft/FocalNet#43]
All checkpoint links lead to the same page:
```HTML
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>PublicAccessNotPermitted</Code>
<Message>Public access is not permitted on this storage account. RequestId:677b1eb8-501e-0054-079c-93e2cc000000 Time:2023-05-31T08:48:21.6368816Z</Message>
</Error>
```

**Comment by Edenzzzz** [comment]
Yeah this is ridiculous

**Comment by jwyang** [comment]
thanks for reminding me. It is because the public access has been turned off per policy. will move the ckpts to huggingface.

**Comment by seewhyjay** [comment]
@jwyang Thanks for the reply! Do you know when the checkpoints will be available on huggingface? The downloads are currently still unavailable.

**Comment by lostkevin** [comment]
@jwyang Do you know when the FocalNet-DINO will be available on hugging face? The uploaded checkpoints are still classification backbones.

**Comment by tea1528** [comment]
@jwyang , FocalNet-Huge ImageNet22K weight seems to be missing from the huggingface while all the other architectures are available (e.g. Base, Large). Is this intentional?

**Comment by jwyang** [comment]
This is not intentionally, I also do not understand that and will upload them to huggingface.
