### ISSUE TITLE
How to download Focal-DINO weights ? Model zoo links throw error

### ISSUE THREAD

**Issue by InternetXplorer** [microsoft/FocalNet#45]
I tried downloading some pretrained weights from the [model zoo of the focal-DINO repo](https://github.com/FocalNet/FocalNet-DINO#model-zoos), but the link throws an error ("Public access is not permitted on this storage account."). I saw that the same issue has been discussed for FocalNet's model zoo, and the answer was to look on huggingface. However I can't find anything on huggingface for the DINO version of FocalNet. Where can I find that ?

**Comment by jwyang** [comment]
Please find the ckpts here: https://huggingface.co/microsoft/focalnet-large-fl4-dino-o365/resolve/main/focalnet_large_fl4_pretrained_on_o365.pth and https://huggingface.co/microsoft/focalnet-large-fl4-dino-o365-cocoft/resolve/main/focalnet_large_fl4_o365_finetuned_on_coco.pth

**Comment by InternetXplorer** [comment]
Thank you very much !
