### ISSUE TITLE
FocalNet-DINO checkpoints from huggingface. config

### ISSUE THREAD

**Issue by JarvisKevin** [microsoft/FocalNet#46]
[06/30/2023] 💥 Please find FocalNet-DINO checkpoints from [huggingface](https://huggingface.co/microsoft). The old links are deprecated.
where is the configuration of this ckpt? https://huggingface.co/microsoft/focalnet-large-fl4-dino-o365/tree/main
and where is the base model's configuration in mmdet's type?
Thanks

**Comment by jwyang** [comment]
Here it is: https://github.com/FocalNet/FocalNet-DINO/blob/main/config/DINO/DINO_5scale_focalnet_large_fl4.py
