### ISSUE TITLE
Cannot download pre-trained weight files from Git repository.

### ISSUE THREAD

**Issue by Gitter03** [microsoft/FocalNet#49]
Hello,

I am trying to download pre-trained weights from the repository (Sparse R-CNN with FocalNet Tiny Backbone pre-trained on COCO object detection). Clicking on the "ckpt" button gives me an error called "PublicAccessNotPermitted". Why are the files not open to the public? Can I download them from somewhere else?

Thanks in advance!

**Comment by jwyang** [comment]
please download it here: https://github.com/microsoft/FocalNet/releases/download/v1.0.1/focalnet_tiny_lrf_sparsercnn_3x.pth
