### ISSUE TITLE
Focal modulation networks for studying the Earth system

### ISSUE THREAD

**Issue by HakamShams** [microsoft/FocalNet#50]
Dear Jwyang, would you add a pointer to refer to our work with Focal Modulation in the context of Earth system?

Project page: https://hakamshams.github.io/Focal-TSMP/
Preprint: https://egusphere.copernicus.org/preprints/2023/egusphere-2023-2422/
Code: https://github.com/HakamShams/Focal_TSMP

Thank you for your work!

**Comment by jwyang** [comment]
thanks for sharing! Added.
