### ISSUE TITLE
Pretrained weights from ImageNet-22K and object365

### ISSUE THREAD

**Issue by zhang-jr** [microsoft/FocalNet#7]
Any plan to release coco detection pretrained weights from ImageNet-22K and object365?

**Comment by jwyang** [comment]
Hi, thanks for your interest, we are planning to release large, xlarge soon, and the huge model as well for the community.

**Comment by zhang-jr** [comment]
Thanks for your reply and sharing.

**Comment by jwyang** [comment]
@zhang-jr , we just release the large, xlarge and huge FocalNets, have a try!

**Comment by zhang-jr** [comment]
@jwyang I really appreciate it!
