### ISSUE TITLE
Custom dataset object detection support 

### ISSUE THREAD

**Issue by Qezrt** [microsoft/FocalNet#8]
Can you please provide a guide including the steps or configurations to do  to be able to fit it with a custom dataset ? THANK YOU

**Comment by jwyang** [comment]
Hi, we deployed our pretrained focalnet to mmdetection. so you can simply follow mmdetection to prepare/register your customized dataset. Please find the details from this page: https://github.com/microsoft/FocalNet/tree/main/detection

**Comment by mattroos** [comment]
@jwyang can you expand on this just a little bit? You use mmdetection, but the mmdetection repo does not include `mmdet/models/backbones/swin_transformer.py`. The SwinTransformer repo has that backbone, but the SwinTransformer repo was forked from mmdetection (when? I don't know how to find out).

So, is the correct approach to clone the SwinTransformer and FocalNet repos, then copy files from FocalNet into SwinTransformer? Or should we clone all three repos and copy files from FocalNet and SwinTransformer into mmdetection? If the latter, which files from SwinTranformer should be copied into mmdetection?--All of them, or some subset?
