### ISSUE TITLE
Will you publish the DINO based model that achieved SOTA on COCO?

### ISSUE THREAD

**Issue by ronslos** [microsoft/FocalNet#9]
Hi, thanks for the interesting and insightful work!
Will you publish code and weights for the DINO based model that achieves SOTA on COCO detection?

**Comment by jwyang** [comment]
thanks for your interest, yes, we will release the large, xlarge and huge models shortly.

**Comment by jwyang** [comment]
HI, @ronslos , we just released the large, xlarge and huge ckpts pretrained on imagenet-22k. Give it a try!

**Comment by YChunag** [comment]
@jwyang , could you please release them for object detection?

**Comment by jwyang** [comment]
Hi, @YChunag , I will release the od pretrained ckpts at some points soon.

**Comment by jwyang** [comment]
Please refer to this repo for the object detection with our FocalNet: https://github.com/FocalNet/FocalNet-DINO

**Comment by Kshitiz-Jain** [comment]
Hello, Thank you for sharing your work.
I wanted to know if the above mentioned models for Object detection has been released.

**Comment by songyuc** [comment]
Hi, @jwyang , what is the "COCO minival" in your our FocalNet: https://github.com/FocalNet/FocalNet-DINO?
I have little knowledge about "COCO minival", as I just head about COCO-val dataset.
